# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8196214579a757cd1c635ec9b2f6f6d329d7749140ffd3358a680e2fadd3bc13e8d3a46ef6652bff030abfcf50deb81947b0ff20367a99349efd8f9bee66e80a

test:
  secret_key_base: f088639d62bb4b8f2941aba5a5107c0ad2e7089f37d69044a270564602e06c621eec98c2fba0a0f5524b448818073231ebd744b51c832b970fa454dd00908643

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
